DHCP improvements.
ivmarkov/edge-net pull request #12
Opened 2023-12-22 18:28 UTC by reitermarkus

Some small improvements to get this working in the `esp-wifi/embassy_access_point` example. 

I guess some changes are not technically necessary to get it working, since I now figured out that the `DHCPOFFER` response needs to be sent as a broadcast, at least if the client IP is `0.0.0.0`.

2023-12-23 09:36 UTC, ivmarkov commented
@reitermarkus Ping me when you are done so that I can start reviewing. Or put the PR in Draft mode until it is ready.

2023-12-23 15:03 UTC, reitermarkus commented
@ivmarkov, I think that's it for now.

2023-12-24 06:36 UTC, ivmarkov requested changes
Cab you revert the signature of the `reply` method to the original one? Or explain which of the new parameters are necessary, and why.

2023-12-24 06:36 UTC, ivmarkov commented on Cargo.toml
> -embassy-time = { version = "0.1", default-features = false }
This currently breaks the CI build because feature `embedded-svc` still needs `embassy-time 0.1`.

I plan to update `embedded-svc` and all `esp-idf-*` crates shortly post Dec 28 though.

2023-12-24 06:36 UTC, ivmarkov commented on edge-dhcp/src/lib.rs
> +    pub fn new_reply<'b>(
This is the one change I have biggest concerns with.

Why is passing all those parameters necessary? 

The whole point of of the `reply` method is that it should be able to assemble a reply to a DHCP Discover/Request message based on the original message sent by the DHCP client, plus **minimal** external information - as in - ideally, only the IP which is to be offered / ack-ed.

If the user want to deeply customize the reply packet, I would suggest the user should just create a packet with `Packet::new` and then assemble it she sees fit.

Therefore, unless there is a really good reason - to pass all these `*addr` parameters (and which of these exactly do you need anyway and why?) I suggest you revert this change.

2023-12-24 06:36 UTC, ivmarkov commented on edge-dhcp/src/lib.rs
> +            Self::MaximumMessageSize(size) => f(&size.to_be_bytes()),
Out of pure curiosity: what are these two things implementing, and are they really necessary?

2023-12-24 06:36 UTC, ivmarkov commented on edge-dhcp/src/server.rs
> +        let message_type = request.options.iter().find_map(|option| {
The changes below are kind of subjective and a matter of personal preference, as all they do is (a) rename a variable to a longer name (b) re-arrange the if logic with an early return (I hope it is still the same) and (c) provide an extra info when the server got a message not for itself.

I'll keep it but in general the smaller the PR, the better to understand what it really addresses.

2023-12-24 09:18 UTC, reitermarkus commented on edge-dhcp/src/server.rs
> +        let message_type = request.options.iter().find_map(|option| {
> kind of subjective

Self-documenting variable names are are objectively more readable.

I can revert the re-arranging and submit it as a separate PR to make it easier to review, if you want.

2023-12-24 09:25 UTC, reitermarkus commented on edge-dhcp/src/lib.rs
> +            Self::MaximumMessageSize(size) => f(&size.to_be_bytes()),
They are not used currently, but iOS sends them and I didn't like seeing unrecognized options. The client identifier should be used together with `chaddr` to uniquely identify the client. The maximum message size allows the client to negotiate a larger message size than 576.

2023-12-24 09:32 UTC, reitermarkus commented on edge-dhcp/src/lib.rs
> +    pub fn new_reply<'b>(
These fields depend on the message type, which isn't passed to this method. They aren't all just copied from the request or set to the IP, as seen in the table in [RFC 2131, section 4.3.1](https://datatracker.ietf.org/doc/html/rfc2131#section-4.3.1).

2023-12-24 09:44 UTC, ivmarkov commented on edge-dhcp/src/lib.rs
> +    pub fn new_reply<'b>(
When the server can lease an IP it will be nott None, and the message type is Ack. And the other way around.

If there are no other arguments to have these parameters (as in, something did nor work for you) let's revert this change.

2023-12-24 09:45 UTC, ivmarkov commented on edge-dhcp/src/server.rs
> +        let message_type = request.options.iter().find_map(|option| {
No. As I said let's keep this change. I have much stronger feelings for the reply method.

2023-12-24 09:53 UTC, reitermarkus commented on edge-dhcp/src/lib.rs
> +    pub fn new_reply<'b>(
`ciaddr` should not be set to the IP in`DHCPOFFER` or `DHCPNAK`, which it currently is. And `yaddr` should not be set in `DHCPNAK` which it currently is.

2023-12-24 09:55 UTC, reitermarkus commented on edge-dhcp/src/lib.rs
> +    pub fn new_reply<'b>(
Oh wait, the IP is `None` when sending `NAK` so it actually is not set. Still, `ciaddr` should not be set when sending `OFFER`.

2023-12-24 09:59 UTC, reitermarkus commented on edge-dhcp/src/lib.rs
> +    pub fn new_reply<'b>(
But even if it works for `NAK` currently due to the IP being `None`, the logic doesn't make sense, since `ciaddr` is not the leased IP but the `ciaddr` from the request.

2023-12-24 10:25 UTC, ivmarkov commented on edge-dhcp/src/lib.rs
> +            Self::MaximumMessageSize(size) => f(&size.to_be_bytes()),
Ok, fair enough.

2023-12-24 13:21 UTC, ivmarkov commented on edge-dhcp/src/lib.rs
> +    pub fn new_reply<'b>(
Sure. But all of this is fixable (as you did) because you have the request message when building the reply. Including the options. No need to pass anything from "outside".

2023-12-24 13:23 UTC, ivmarkov commented
LGTM. Will merge later today once I'm back. Hope you don't mind f if I don't merge the `embassy-time` upgrade immediately, but in a couple of weeks. Else I need to temporarily remove the `embedded-svc` feature, which is annoying.

2023-12-24 16:27 UTC, merged