edge-http: make fields in {Req,Resp}Headers non-optional
ivmarkov/edge-net pull request #37
Opened 2024-10-10 03:10 UTC by showier-drastic

Ensures that the {Req,Resp}Headers is always complete and adheres to the HTTP spec. Saves a lot code from dealing with `Option`s.

Also, `send_status_line` is removed, and inlined into `send_request` and `send_status`. This cuts ~80 lines from the code, which is nice.

2024-10-10 04:56 UTC, ivmarkov requested changes
My main concern is as expressed below - we are deepening an already existing memory consumption problem. `Headers`, with N = 60 is 60*8 = 480 bytes, which when created in a future often double its size due to Rust not being very efficient wr.t. futures' size.

We must have a way to pre-create `RequestHeaders` and `ResponseHeaders`, or else we won't be able - in future - to pre-create them outside the async code and then possibly pool them. We are also removing this existing option for users who would like to do it, and who are not using the `Connection` machinery altogether.

2024-10-10 04:56 UTC, ivmarkov commented on edge-http/src/io.rs
> +        let mut headers = Headers::<'b, N>::new();
This is not so ideal, in that the `Headers` type is not so small, and creating it elsewhere in `async` methods (in `Connection`) is already giving us troubles (large futures) that I have to solve.

With this change, we are actually deepening the problem, moving the issue down to `RequestHeaders` and `ResponseHeaders`, in that they no longer can be pre-created outside the future context either.

2024-10-10 06:45 UTC, showier-drastic commented
Thanks for the review! I understand your point. I would like to know, in the first place, do you think that making the fields non-`Option` makes sense? If yes, then maybe I can spend some time to think about how to let the user allocate them before parsing.

2024-10-10 07:10 UTC, ivmarkov commented
> Thanks for the review! I understand your point. I would like to know, in the first place, do you think that making the fields non-`Option` makes sense? If yes, then maybe I can spend some time to think about how to let the user allocate them before parsing.

It certainly makes the code simpler and easier to reason about. (My one little concern is the `Method` field, where I'm not sure we have - in the `Method` enum, all HTTP 1.1 methods, but I guess that can be double-checked and fixed if methods are still missing.  Or maybe we can introduce an `Unknown` method?)

Otherwise - between introducing something like `RequestLine` and wrapping this whole thing in an `Option` (but then, would the code become any shorter than it is now?) - and just using default values for `http11` and `Method` (ditto for the status line case) I don't think there are that many options? And if we use default values, would that be a net win? Maybe, not sure.

Open to any other suggestions though.

2024-10-10 14:46 UTC, showier-drastic commented
This might indeed be unsolvable, other than using `MaybeUninit`, which is unsafe and does not look worthwhile to be used here.

How about this:
* Remove `Option`s as in this PR;
* Give some default values in `new`, rather than `None`;
* Let `receive` to be an instance method (same as the current master branch) to avoid allocation problem.

2024-10-10 20:36 UTC, ivmarkov requested changes
Please restore all const constructors and the calls to those. :-)

The rest looks fine.

2024-10-10 20:36 UTC, ivmarkov commented on edge-http/src/lib.rs
> -    /// Create a new RequestHeaders instance for HTTP/1.1
Actually this is a bad idea. `Default::default()` is a trait method, and as such cannot be `const`. Meaning, we can no longer create the request and the response in a const context. 

Implementing a `const new` constructor, and then delegating to it from `Default::default` is pretty idiomatic, especially in Embedded Rust.

2024-10-10 20:36 UTC, ivmarkov commented on edge-http/src/lib.rs
> -    /// Create a new RequestHeaders instance for HTTP/1.1
And restore the calls to `new`. Calling `default` is not any better, nor is any more idiomatic.

2024-10-11 01:29 UTC, showier-drastic commented
Did not know this about `new` vs `default` and the relationship to `const`. Really learned a lot :)

2024-10-11 07:44 UTC, merged

2024-10-15 19:36 UTC, DaneSlattery commented on edge-http/src/lib.rs
> -    /// Create a new RequestHeaders instance for HTTP/1.1
https://github.com/rust-lang/rust/issues/67792 for curiousity sake